<!--
/**
* NOTICE OF LICENSE
*
* Magento extension which extracts a product feed from Magento, imports the feed into Fruugo and uses the Fruugo Order API to export all Fruugo orders into Magento.
*
* Copyright (C) 2015  Fruugo.com Ltd
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License along with this program.
* If not, see <http://www.gnu.org/licenses/>.
*/
-->
<?php

    echo '<p>Fruugo Order Id: ' . $this->getFruugoOrderId() . '</p>';
    echo '<p>Order Items:</p>';

    $order = $this->getOrder();
    foreach($order->getAllItems() as $orderItem) {
        echo '<p>Fruugo Product Id: ' . $orderItem->getFruugoProductId() . '</p>';
        echo '<p>Fruugo Sku: ' . $orderItem->getFruugoSkuId() . '</p>';
    }

    $fruugoOrderId = $this->getFruugoOrderId();
    $shipmentIds = $order->getFruugoShipmentIds();

    if (count($shipmentIds) > 0)
    {
        foreach ($shipmentIds as $shipmentId)
        {
            $link = '<p><a href="';

            $link .= Mage::getUrl('integration/packinglist/getPackingList', array('fruugoOrderId'=>$fruugoOrderId, 'shipmentId'=>$shipmentId));

            $link .= '">Download Packing List</a></p>';

            echo $link;
        }
    }
